cabal-version:       2.4
name:                WID3001-Assignment
version:             0.1.0.0

library
  exposed-modules:     
    AST
    Parser
    Tokenizer
    EvaluatorCore
  build-depends:       
    base ^>=4.19
  hs-source-dirs:      
    src
  default-language:    
    Haskell2010

executable WID3001-Assignment
    main-is: Main.hs
    build-depends: base ^>=4.19
    hs-source-dirs: app
    default-language: Haskell2010